baseurl = "http://0xack13.github.io/0xackBlog/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"

[params]
  description = "Saleh's Awesome Hugo Site"
  author = "Saleh Albatati"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
