baseurl = "http://0xack13.github.io/0xackBlog/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"
canonifyurls = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  description = "Saleh's Awesome Hugo Site"
  author = "Saleh Albatati"
